apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: c3FsMDE=        # Base64 encoded value of "sql01"
  MYSQL_USER: dXNlcjE=            # Base64 encoded value of "user1"
  MYSQL_PASSWORD: MTIz            # Base64 encoded value of "123"
  MYSQL_ROOT_PASSWORD: MTIz       # Base64 encoded value of "123"
